"""
Recommendation history model
----------------------------

This model stores historical recommendations for individual tickers.
Each entry corresponds to a recommendation generated by the crew,
along with the price and percentage change at the time of the recommendation
and the rationale provided.  This table is used to present a history
of changes for a given ticker in the frontend.
"""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Text

from .base import Base


class RecommendationHistory(Base):
    """Historical record of individual ticker recommendations."""

    __tablename__ = "recommendation_history"

    id = Column(Integer, primary_key=True, autoincrement=True)
    analysis_id = Column(String, ForeignKey("analyses.id"), nullable=False)
    ticker = Column(String, nullable=False)
    rating = Column(String, nullable=False)
    current_price = Column(Float, nullable=True)
    percent_change = Column(Float, nullable=True)
    report_time = Column(DateTime, nullable=True)
    reason = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)